apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment
  labels:
    app: jboss-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jboss-app
  template:
    metadata:
      labels:
        app: jboss-app
    spec:
      containers:
      - name: jboss
        image: image-registry.openshift-image-registry.svc:5000/testpipeline/hello:latest
        ports:
        - containerPort: 8080
